// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4ZMVQ0qRI_lb4q_48mryJgTYvmRdHvJo',
    appId: '1:861218934239:android:afc7715532b0a3bed7486a',
    messagingSenderId: '861218934239',
    projectId: 'app-talk-3caf8',
    databaseURL: 'https://app-talk-3caf8.firebaseio.com',
    storageBucket: 'app-talk-3caf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD23vaA3wqOI7DCDQLINJdGzG_XPmSN62E',
    appId: '1:861218934239:ios:d053aa93545a8c25d7486a',
    messagingSenderId: '861218934239',
    projectId: 'app-talk-3caf8',
    databaseURL: 'https://app-talk-3caf8.firebaseio.com',
    storageBucket: 'app-talk-3caf8.appspot.com',
    iosClientId: '861218934239-u8umsu0m217mrcdgsqbrd75ap9qt68d9.apps.googleusercontent.com',
    iosBundleId: 'com.hugoteam.visitors',
  );
  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyD7RA3xVotm_38mucBi38SsM1LgnR_jOgw",
      authDomain: "app-talk-3caf8.firebaseapp.com",
      databaseURL: "https://app-talk-3caf8.firebaseio.com",
      projectId: "app-talk-3caf8",
      storageBucket: "app-talk-3caf8.appspot.com",
      messagingSenderId: "861218934239",
      appId: "1:861218934239:web:392cc12651dca289d7486a",
      measurementId: "G-GRG5Z3WYP3"
  );
}
